"use client"

import { Roboto } from "next/font/google";
import "./styles/reset.css";
import "./Main.module.scss"
import Navbar from "./components/Navbar"
import Splash from "./components/Splash"
import { usePathname } from "next/navigation";
import { useEffect } from "react";
import { useState } from "react";
import Footer from "./components/Footer";


// const roboto = Roboto({ subsets: ["latin"], weight: ["100", "300", "400", "500" , "700" ,"900" ]});
// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };


export default function RootLayout({ children }) {
  const pathname = usePathname()
  const isHome = pathname === "/"
  const [isLoading, setIsLoading] = useState(isHome)


  useEffect(() => {
    if (isLoading) return
  }, [isLoading])

  return (
    <html lang="en">
      <body className="Body">
      {isLoading && isHome ? (
        <Splash/>
      ) : (
        <>
          <Navbar />
          {children}
          <Footer />
        </>
      )}



      </body>
    </html>
  );
}
